[workspace]
members = ["suppaftp", "suppaftp-cli"]
resolver = "2"

[workspace.package]
version = "6.0.4"
edition = "2021"
authors = [
  "Christian Visintin <christian.visintin@veeso.dev>",
  "Matt McCoy <mattnenterprise@yahoo.com>",
]
repository = "https://github.com/veeso/suppaftp"
license = "MIT OR Apache-2.0"
keywords = ["ftp", "ftps", "network-protocol", "async", "ftp-client"]
categories = ["asynchronous", "network-programming"]
