[package]
name = "suppaftp"
version = "4.1.3"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>", "Christian Visintin <christian.visintin1997@gmail.com>"]
edition = "2021" 
documentation = "https://docs.rs/suppaftp/"
repository = "https://github.com/veeso/suppaftp"
description = "A super FTP/FTPS client library for Rust"
include = ["src/**/*", "cli/**/*", "LICENSE-APACHE", "LICENSE-MIT", "README.md", "CHANGELOG.md"]
readme = "README.md"
license = "Apache-2.0/MIT"
keywords = ["ftp", "ftps", "network-protocol", "async"]
categories = ["asynchronous", "network-programming"]

[lib]
name = "suppaftp"
path = "src/lib.rs"

[[bin]]
name = "suppaftp"
path = "cli/main.rs"
required-features = ["secure", "cli-bin"]

[dependencies]
async-std = { version = "^1.10.0", optional = true }
async-native-tls = { version = "^0.4.0", optional = true }
chrono = "^0.4.19"
lazy_static = "^1.4.0"
native-tls = { version = "^0.2", optional = true }
pin-project = { version = "^1.0.8", optional = true }
regex = "^1.4.2"
rpassword = { version = "5.0.1", optional = true }
thiserror = "^1.0.20"

[dev-dependencies]
async-attributes = "1.1.2"
pretty_assertions = "^1.0.0"
rand = "0.8.4"

[features]
# Enable async support for suppaftp
async = ["async-std", "pin-project"]
async-secure = ["async-std", "async-native-tls", "pin-project"]

# Enable support of FTPS which requires native-tls (openssl is required on Linux)
secure = ["native-tls"]

# Must be enabled whenever testing with docker containers
with-containers = []

# Add debug output (to STDOUT) of commands sent to the server
# and lines read from the server
debug_print = []

# Don't enable this feature; is used by suppaftp binary only
cli-bin = ["rpassword"]
