[package]
name = "suppaftp"
version = "4.5.0"
authors = ["Christian Visintin <christian.visintin1997@gmail.com>", "Matt McCoy <mattnenterprise@yahoo.com>"]
edition = "2021" 
documentation = "https://docs.rs/suppaftp/"
repository = "https://github.com/veeso/suppaftp"
description = "A super FTP/FTPS client library for Rust"
include = ["src/**/*", "cli/**/*", "LICENSE-APACHE", "LICENSE-MIT", "README.md", "CHANGELOG.md"]
readme = "README.md"
license = "Apache-2.0/MIT"
keywords = ["ftp", "ftps", "network-protocol", "async"]
categories = ["asynchronous", "network-programming"]

[lib]
name = "suppaftp"
path = "src/lib.rs"

[[bin]]
name = "suppaftp"
path = "cli/main.rs"
required-features = ["secure", "cli-bin"]

[dependencies]
chrono  = "^0.4"
lazy-regex = "^2.3"
log = "^0.4"
thiserror = "^1"
# async
async-std = { version = "^1.10", optional = true }
async-native-tls-crate = { package = "async-native-tls", version = "^0.4", optional = true }
async-tls = { version = "^0.11", optional = true }
pin-project = { version = "^1", optional = true }
# secure
native-tls-crate = { package = "native-tls", version = "^0.2", optional = true }
rustls-crate = { package = "rustls", version = "^0.20", optional = true }
# cli-bin
env_logger = { version = "^0.9", optional = true }
rpassword = { version = "5.0.1", optional = true }

[dev-dependencies]
async-attributes = "1.1.2"
env_logger = "^0.9.0"
pretty_assertions = "^1.0.0"
rand = "^0.8.4"
serial_test = "^0.8.0"
webpki-roots = "0.22.5"

[features]
# Enable async support for suppaftp
async = ["async-std", "pin-project"]
async-default-tls = [ "async-native-tls" ]
async-native-tls = [ "async-native-tls-crate", "async-secure" ]
async-rustls = [ "async-tls", "async-secure" ]
async-secure = [ "async" ]

# Enable deprecated FTP/FTPS methods
deprecated = []

# Enable support for FTPS which requires native-tls (openssl is required on Linux) or RustTLS
default-tls = [ "native-tls" ]
native-tls = [ "native-tls-crate", "secure" ]
native-tls-vendored = [ "native-tls", "native-tls-crate/vendored" ]
async-native-tls-vendored = [ "async-native-tls", "async-native-tls-crate/vendored" ]
rustls = [ "rustls-crate", "secure" ]
secure = []

# Disable logging
no-log = [ "log/max_level_off" ]

# Must be enabled whenever testing with docker containers
with-containers = []

# Don't enable this feature; is used by suppaftp binary only
cli-bin = [ "env_logger", "rpassword"]
